Add dynamic announcements
prestodb/presto-manager pull request #58
Opened 2017-08-11 20:02 UTC by jirassimok

2017-08-21 19:18 UTC, cawallin requested changes
Nice job getting dynamic announcements working!

2017-08-25 19:05 UTC, jirassimok commented on presto-manager-controller/src/main/java/com/teradata/prestomanager/controller/DiscoveryAgentMap.java
> +            Agent agent = new Agent(uri, isCoordinator, id);
That's not currently included in the dynamic announcement, but shouldn't be too hard to add. Until then, I'd rather remove it, so it doesn't _look_ like we support that.

2017-08-25 19:06 UTC, jirassimok commented on presto-manager-agent/src/main/java/com/teradata/prestomanager/agent/announcement/DynamicAnnouncementBinder.java
> + * dynamicAnnouncementBinder(binder)
All right.

2017-08-25 21:36 UTC, jirassimok commented
I've fixed the typo that was causing the dynamic announcement to be created incorrectly (the property name was wrong).

I've also added a new commit making the Controller's methods use `String` instead of `UUID` for node IDs, because Airlift's `ServiceDescriptor` (the basis for the discovery announcements) uses `String`.

This should be tested on multiple Agents and with proper configuration before it is merged, but I believe it should work.

2017-08-25 21:37 UTC, jirassimok commented on presto-manager-agent/src/main/java/com/teradata/prestomanager/agent/announcement/DynamicAnnouncementBinder.java
> + * dynamicAnnouncementBinder(binder)
All right.

2017-08-31 16:59 UTC, merged

2017-08-31 16:59 UTC, cawallin commented
Merged, thanks!